apiVersion: apps/v1
kind: Deployment
metadata:
    name: sa-frontend
spec:
    selector:
        matchLabels:
            app: sa-frontend
    replicas: 2
    minReadySeconds: 15
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                app: sa-frontend
        spec:
            containers:
                - image: pi3sme/sentiment-analysis-frontend:green
                  imagePullPolicy: Always
                  name: sa-frontend
                  env:
                      - name: WEBAPP_HOST
                        value: "43.132.179.204"
                      - name: WEBAPP_PORT
                        value: "3000"
                  ports:
                      - containerPort: 80

